const Accounts = [
  {
    id: "1",
    username: "Muhammad",
    email: "muhammad@gmail.com",
    password: "1234567",
    role: "supervisor",
  },

  {
    id: "2",
    username: "farid",
    email: "farid@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "3",
    username: "lutfi",
    email: "lutfi@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "4",
    username: "zimam",
    email: "zimam@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "5",
    username: "fikri",
    email: "fikri@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "6",
    username: "wahyu",
    email: "wahyu@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "7",
    username: "zakyy",
    email: "zakyy@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "8",
    username: "izhar",
    email: "izhar@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "9",
    username: "dani",
    email: "dani@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "10",
    username: "Fahri",
    email: "Fahri@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "11",
    username: "Rendy",
    email: "Rendy@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "12",
    username: "Rizal",
    email: "Rizal@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "13",
    username: "Fahrian",
    email: "Fahrian@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "14",
    username: "Topek",
    email: "Topek@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "15",
    username: "Bitang",
    email: "Bitang@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "16",
    username: "Hilmi",
    email: "Hilmi@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "17",
    username: "Ave",
    email: "Ave@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "18",
    username: "Samuel",
    email: "Samuel@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "19",
    username: "Farel",
    email: "Farel@gmail.com",
    password: "1234567",
    role: "operator",
  },
  {
    id: "20",
    username: "Novam",
    email: "Novam@gmail.com",
    password: "1234567",
    role: "operator",
  },
];

export default Accounts;
